import './globals.css';
import { ThemeProvider } from '@mui/material';
import JobProvider from './providers/JobProvider';
import QuestionProvider from './providers/QuestionProvider';
import UserDetailsProvider from './providers/UserDetailsProvider';
import theme from './theme';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true}>
        <ThemeProvider theme={theme}>
          <UserDetailsProvider>
            <JobProvider>
              <QuestionProvider>{children}</QuestionProvider>
            </JobProvider>
          </UserDetailsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
