import { Inter } from 'next/font/google';
import Container from '@mui/material/Container';
import './globals.css';
import JobProvider from './providers/JobProvider';
import QuestionProvider from './providers/QuestionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <JobProvider>
          <QuestionProvider>
            <Container maxWidth='md'>{children}</Container>
          </QuestionProvider>
        </JobProvider>
      </body>
    </html>
  );
}
